# 1. Simple Linear Regression with scikit-learn

Import Packages and Classes

In [4]:
# to reduce the amount of typing we have to do, to make the code more readable 
# use from keyword to import LinearRegression class from scikit-learn

In [5]:
import numpy as np                                          
from sklearn.linear_model import LinearRegression     

In [6]:
# Two inputs; Regressor(x), Predictor(y)
# The predictor(y) - one-dimensional array, use np.array() 
# The regressors(x) - two-dimensional array, use np.array().Transpose the array using .reshape((-1,1))

In [7]:
y = np.array([3, 9, 20, 24, 30, 38])
x = np.array([1, 2, 3, 4, 5, 6]).reshape(-1, 1)

Exercise 1: NumPy Arrays

1. Print x and y and evaluate the shape of the arrays.

In [8]:
print(x)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [9]:
print(y)

[ 3  9 20 24 30 38]


In [12]:
x.shape

(6, 1)

In [13]:
y.shape

(6,)

2. How many columns do each of the arrays have?

In [20]:
x.shape[1]

1

In [25]:
y.shape

(6,)

In [23]:
# only 1 dimension — 6 elements in one row, no columns
# Python throws an error because there is no index 1 in the shape tuple (5,)

y.shape[1]

IndexError: tuple index out of range

3. And how many rows?

In [26]:
x.shape[0]

6

In [27]:
y.shape[0]

6

4. What are the dimensions of the arrays?

In [29]:
x.ndim

2

In [30]:
y.ndim

1

5. Create a one-dimensional NumPy array with the values between 0 and 100 with steps of 5 in between. 

In [38]:
a = np.arange(0, 100, 5)
print(a)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


6. Transpose the NumPy array you created in the previous exercise. What are the dimensions of the array now?

In [39]:
b = a.T
print(b)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [41]:
print("Original shape:", a.shape)
print("Transposed shape:", b.shape)

Original shape: (20,)
Transposed shape: (20,)
